GET  http://localhost:9191/posts/6350f09c7ba9e0a43333a761/comments

###

POST http://localhost:9191/posts/6350f09c7ba9e0a43333a761/comment
Content-Type: application/json

{
    "comment": "A commnet for a post",
    "name": "Srikanth Kumar",
     "email": "wpsrikanth@gmail.com",
    "image": "http://www.gravatar.com/avatar/2c4d15e5f863923c0f8dab3b1942ee39"
}

###

DELETE http://localhost:9191/posts/6354e155182ad57a8f52b885
###
POST http://localhost:9191/posts/
Content-Type: application/json

{
    "title": "23Oct",
    "contents": "23 Oct f m1 is really challenging",
    "email" : "wpsrikanth@gmail.com",
    "category" : "misc",
    "name": "not"
}